### PR TITLE
Updating dependencies to avoid vulnerability

### PR DESCRIPTION
**Pull request by couimet**
References:
- https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
- isaacs/node-mkdirp@c5b97d1

I also bumped version from 1.0.1 to 1.0.2

### CODE REVIEW

**Comment by couimet** [comment]
@mmouterde When (if ?) you merge, will the npm registry will automatically get a new version ?

**Comment by couimet** [comment]
@mmouterde I couldn't find tests to run. How can I validate my changes are OK ?

**Comment by couimet** [comment]
This PR should solve #3 .

**Comment by mmouterde** [comment]
I'm no longer active on this project.
@calebcartwright could you test this PR ?
@couimet @calebcartwright would you become maintainers ?!

**Comment by calebcartwright** [comment]
@mmouterde - tested the change and no issues, also looking forward to this being merged and published!

I'm afraid I'll have to decline your offer to take on a maintainership role for this project. I assumed this was no longer supported so I'd started working on my own. I feel like there's a chunk of changes that would need to be made here like updating to leverage new Mocha custom reporter features, mkdirp 1.x+, supporting TypeScript source files, adding unit tests, etc. and I can't rationalize trying to do all that here and achieve those same goals in two different packages.

Thank you for the time and effort you put into this package though, it's definitely been a big help getting test results integrated in Sonar!

**Comment by couimet** [comment]
I'm willing to become maintainer of this project; assuming people have reasonable expectations about the time I can devote to it.

My main motivation is to be able to merge my PR and get rid of our `D` Security grade in SonarQube because we currently rely on https://github.com/mmouterde/mocha-sonarqube-reporter in our project. ;-)

**Comment by couimet** [comment]
> @mmouterde - tested the change and no issues, also looking forward to this being merged and published!

@calebcartwright Do you have basic instructions about how you tested the change ?

**Comment by couimet** [comment]
@mmouterde 

1. Do you happen to have tests that you used when you developed this project ?(Even if they exist outside this repo ?)

I saw the _fake_ `npm test` script (https://github.com/mmouterde/mocha-sonarqube-reporter/blob/master/package.json#L7). Do you have something more than that ?

2. I'd also need instructions (and rights?) about packaging + deploying a new version on https://www.npmjs.com/package/mocha-sonarqube-reporter

**Comment by mmouterde** [comment]
@couimet  

- You get the contributor rights on this repo, I guess you could merge future PRs. Let me know. (...I merged to early, I would be a good test)

- So sorry,  4 years after, I have no test dataset any more, the code is drastically copied from https://github.com/qingguo-yu/mocha-sonar-generic-test-coverage-file/blob/master/index.js but there is no test too...

**Comment by calebcartwright** [comment]
@couimet 

> @calebcartwright Do you have basic instructions about how you tested the change ?

Nothing fancy really as a small patch bump of mkdirp is highly unlikely to cause any functional breakage. Given the nature of the change, I just ran a live test using your branch in one of my projects and validated the creation of the output dir and file.

**Comment by couimet** [comment]
I created a new release:
https://github.com/mmouterde/mocha-sonarqube-reporter/releases/tag/1.0.2

**Comment by couimet** [comment]
@mmouterde What action do I need to perform to update https://www.npmjs.com/package/mocha-sonarqube-reporter so it shows version 1.0.2 ?

**Comment by mmouterde** [comment]
You need to `npm publish` it. I'm not sure how to give you right to do that. Could you try and share the result ?

**Comment by mmouterde** [comment]
Ok I have to run `npm owner add`
Could you send me your npmjs.org id ?

**Comment by couimet** [comment]
> Ok I have to run `npm owner add`
> Could you send me your npmjs.org id ?

My npmjs handle is couimet (same as Github).

**Comment by mmouterde** [comment]
Done ! 
You should be able to publish.

**Comment by couimet** [comment]
@mmouterde I checked out `master` and ran `npm publish`.

This is what I got:
```
❯ npm publish
npm notice
npm notice 📦  mocha-sonarqube-reporter@1.0.2
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE
npm notice 3.9kB index.js
npm notice 680B  package.json
npm notice 1.7kB README.md
npm notice === Tarball Details ===
npm notice name:          mocha-sonarqube-reporter
npm notice version:       1.0.2
npm notice package size:  2.8 kB
npm notice unpacked size: 7.3 kB
npm notice shasum:        12d9e1b61bf7391f808a12bf32b360c4b2dd5974
npm notice integrity:     sha512-X6WA0BXSlL7qs[...]GPHW6SFdzm5hQ==
npm notice total files:   4
npm notice
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/mocha-sonarqube-reporter - Not found
npm ERR! 404
npm ERR! 404  'mocha-sonarqube-reporter@1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxx/.npm/_logs/2020-09-17T14_55_40_253Z-debug.log
```

What step am I missing ?

**Comment by mmouterde** [comment]
@couimet .. no idea
I've just run the same command, and that works : 

```
~/projects/mocha-sonarqube-reporter$ npm publish
npm notice 
npm notice 📦  mocha-sonarqube-reporter@1.0.2
npm notice === Tarball Contents === 
npm notice 1.1kB LICENSE     
npm notice 3.9kB index.js    
npm notice 680B  package.json
npm notice 1.7kB README.md   
npm notice === Tarball Details === 
npm notice name:          mocha-sonarqube-reporter                
npm notice version:       1.0.2                                   
npm notice package size:  2.8 kB                                  
npm notice unpacked size: 7.3 kB                                  
npm notice shasum:        0cde59b995f4a99f468e0361ef77453648a67f19
npm notice integrity:     sha512-YxyaBYQDnxFu3[...]LDTvGWLrqFfmg==
npm notice total files:   4                                       
npm notice 
+ mocha-sonarqube-reporter@1.0.2
```

**Pull request merged**
